// const GOOGLE_PLACES_API_KEY = 'AIzaSyCyVnfYV60g1RkGSJmBCof5YvOaOCU6SBM';
const GOOGLE_PLACES_API_KEY = 'AIzaSyCm8LVgXXLesWdJZboaavAmLgvT8cVtXD0';
module.exports = {
  GOOGLE_PLACES_API_KEY: GOOGLE_PLACES_API_KEY
}
